### ISSUE TITLE
Specify how config is loaded from json file

### ISSUE THREAD

**Issue by watsonmw** [detro/jsonconf#4]
It would be immensely & powerfully useful to have a file that controls how config is loaded and in which order.  A user would simply put a 'whoami.json' or perhaps
'whoareyouandwhatareyoudoinghere.json' file in their home directory and that would load a preset configuration with overrides on the order and priority of the other config files loaded. 

Thank you sincerely,
Mark

**Comment by detro** [comment]
Having a `~/.myproject.json` file would definitely be possible. But I'd argue you could do that by setting the "user" file to be just that. But in your defence, that would make it impossible to have both.

Regarding the "order" in which things are applied, I feel like that should be something you define when you include the library in your project. Not something you control from the outside.

Counter-example?

**Comment by watsonmw** [comment]
I'm just being a jerk as usual :)

To be serious, it's hard to go wrong having the application programmatically deciding how to load it's configuration.

**Comment by detro** [comment]
I think at least your first point it's fair (not to mention easy to implement).
The `JSONConfBuilder` could accept multiple `user files`. The infrastructure to do multiple UNIONS it's practically already there.

**Comment by bpossolo** [comment]
Can you add a command line option to read from an XML file instead? I prefer the verbosity. 

Support for config level variables would be awesome too! I think you should auto-detect cyclic references like this: 
A=foo{B}
B=bar{A}

we are finding that our programmers get so confused by the config files in our other projects that they often make this sort of mistake.

**Comment by detro** [comment]
XML? no!

I DO support references to other config options:

```
{
  "var" : "val".
  "obj" : {
    "ref" : "@var"
  }
}
```

where `obj.ref` will resolve to `val`.

Currently resolving cycles is a TODO.
